# Generated by Django 5.2 on 2025-05-27 08:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Due Amount'),
        ),
    ]
